# Generated by Django 5.1.6 on 2025-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('player1_username', models.CharField(max_length=150)),
                ('player2_username', models.CharField(blank=True, max_length=150, null=True)),
                ('paddle_touches', models.IntegerField(default=0)),
                ('fastest_ball_speed', models.FloatField(default=0.0)),
                ('avg_reaction_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('player1_username', models.CharField(max_length=150)),
                ('player2_username', models.CharField(blank=True, max_length=150, null=True)),
                ('outcome', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Draw', 'Draw')], max_length=10)),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('most_touches', models.IntegerField(default=0)),
                ('most_wins', models.IntegerField(default=0)),
                ('longest_win_streak', models.IntegerField(default=0)),
                ('time_played', models.DurationField(default=0)),
            ],
        ),
    ]
