# Generated by Django 5.1.6 on 2025-03-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesessionstats',
            name='avg_reaction_time',
        ),
        migrations.RemoveField(
            model_name='gamesessionstats',
            name='fastest_ball_speed',
        ),
    ]
